### ISSUE TITLE
Build fails with #error LWIP_SOCKET_OFFSET does not work with external FD_SET!

### ISSUE THREAD

**Issue by IainColledge** [paoloach/ESP8266-open-rtos#5]
With a clone of the Espressiff RTOS dated 16/04/19 from

https://github.com/espressif/ESP8266_RTOS_SDK

And the latest plugin when building a freshly created project the build fails with:

```
In file included from C:\msys32\home\Iain\esp\ESP8266_RTOS_SDK\components\esp_http_client\lib\http_auth.c:21:0:
C:\msys32\home\Iain\esp\ESP8266_RTOS_SDK\components\lwip\lwip\src\include/lwip/sockets.h:452:2: error: #error LWIP_SOCKET_OFFSET does not work with external FD_SET!
 #error LWIP_SOCKET_OFFSET does not work with external FD_SET!
  ^
mingw32-make.exe[2]: *** [httpClient\CMakeFiles\espHttpClient.dir\build.make:75: httpClient/CMakeFiles/espHttpClient.dir/C_/msys32/home/Iain/esp/ESP8266_RTOS_SDK/components/esp_http_client/lib/http_auth.c.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:935: httpClient/CMakeFiles/espHttpClient.dir/all] Error 2
```

Please advise.

**Comment by paoloach** [comment]
Hi Iain,

the problem is that espressif continuously update  the repository. When
released,  the plugin was working, now, after update the repository, again
it doesn't work.

I will fix the problem in few days and I will add in the note the RTOS
repository commit used for test.

Anyway, thank for notify the problem.

Paolo



Il giorno mar 16 apr 2019 alle ore 16:53 Iain Colledge <
notifications@github.com> ha scritto:

**Comment by IainColledge** [comment]
Just like before with their upgrade to 3.1 I think you defo need to note the snapshot and put instructions how people can ensure they get that one when setting up.

Appreciate your work as always and looking forward to trying your plugin out for real.

**Comment by IainColledge** [comment]
Just checked if it worked with the latest release 3.1 obtained with:

`git clone -b v3.1 https://github.com/espressif/ESP8266_RTOS_SDK.git`

But alas no as Cmake errors with:

```
CMake Error at httpClient/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: espHttpClient


CMake Error at httpServer/CMakeLists.txt:8 (add_library):
  No SOURCES given to target: espHttpServer


CMake Error at mqtt/CMakeLists.txt:25 (add_library):
  No SOURCES given to target: mqtt


CMake Error at ringbuffer/CMakeLists.txt:8 (add_library):
  No SOURCES given to target: espRingbuf
```
